version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: expo
    versions:
    - 40.0.1
    - 41.0.0
  - dependency-name: react-native-screens
    versions:
    - 2.18.0
    - 2.18.1
    - 3.1.0
  - dependency-name: react-native-gesture-handler
    versions:
    - 1.10.0
    - 1.10.1
    - 1.10.2
    - 1.9.0
  - dependency-name: react-native-svg
    versions:
    - 12.1.0
  - dependency-name: react-native-vector-icons
    versions:
    - 8.0.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: react-navigation
    versions:
    - 4.4.3
